### ISSUE TITLE
NormalTangentTest.gltf does not appear as expected

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#5] opened 2018-01-19 13:35 UTC
I tried to display [NormalTangentTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest) using PlayCanvas glTF Loader.
However, it seems to be different from the expected result.

[PlayCanvas glTF Loader + NormalTangentTest.gltf result:](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF-Binary)
![image](https://user-images.githubusercontent.com/1833979/35153137-94efaa86-fd68-11e7-960e-381676406879.png)

[Expected result:](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest)
![image](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/NormalTangentTest/screenshot/screenshot.png)

Please see below for the purpose of this test.
https://emackey.github.io/testing-pbr/normal-tangent-readme.html
https://emackey.github.io/testing-pbr/normal-tangent-test.html

**Comment by willeastcott** [comment] 2018-01-19 23:15
It looks like the gltf file doesn't contain the tangents. So they'll be generated via the [pc.calculateTangents](https://developer.playcanvas.com/en/api/pc.html#calculateTangents) function. I wonder if there's a problem with our implementation.

https://github.com/playcanvas/engine/blob/master/src/scene/procedural.js#L92

It could also be something else. @guycalledfrank - I'd love to get your thoughts on this.

**Comment by cx20** [comment] 2018-03-03 07:47
A new test model "[Normal-Tagnent Mirror Test](https://github.com/emackey/glTF-Sample-Models/tree/551d7ab2fc02631ee06f88d8aef6d503b24bbc68/2.0/NormalTangentMirrorTest)" is about to be added to [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models). I added this model to [gltf-test](https://github.com/cx20/gltf-test#agi-sample-models) and tried it. PlayCanvas seems to display a new test model without problems.

https://github.com/cx20/gltf-test#agi-sample-models
![image](https://user-images.githubusercontent.com/1833979/36931806-5d1515a0-1f01-11e8-8592-f9d2bfbaf504.png)

I do not understand the difference between these two models, but I think that it is a hint for problem solving.

/cc @emackey Do you have any advice?

**Comment by emackey** [comment] 2018-03-03 14:34
Yes.  The new model (Mirror Test) supplies tangents, and will only display correctly if the supplied tangents are used correctly.

The old model doesn't supply tangents, and tests the engine's ability to generate tangents as needed.  Ironically, for many engines, generating the tangents appears to be the better-supported path, although you would think they would be harder to calculate.  Using the supplied tangents is causing a lot of failures.  Except in PlayCanvas, where from these test results it looks like the supplied tangents work fine and the generated tangents are not correct.

Cesium will have a fix for the new model in 1.44.  Here's the corrected code from the next version of Cesium:

https://github.com/AnalyticalGraphicsInc/cesium/blob/d85c9f11182cfdad3bacf53df1a99a7dbe122c1e/Source/ThirdParty/GltfPipeline/processPbrMetallicRoughness.js#L422-L450

In particular, note the middle part of this, where `hasTangents` is false.  We end up using `GL_OES_standard_derivatives` to calculate the tangents in screen space in the fragment shader, and systems that don't support that extension don't get normal maps unless tangents are supplied.

If you generate the correct tangent vectors, `NormalTangentTest` should pass.  Easier said than done 😄

**Comment by emackey** [comment] 2018-03-03 14:39
Looking at the failed PlayCanvas result, I notice it looks a lot like when people use a DirectX normal map instead of an OpenGL one.  Try flipping your Y vector (flip the intensity of the green channel of the normal map, but only for generated tangents).

**Comment by willeastcott** [comment] 2018-03-03 18:24
I just negated the Y component of the sampled normal map in [this shader chunk](https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/normalMapFloat.frag) and, as you predicted, all is well!

![image](https://user-images.githubusercontent.com/697563/36937701-3c6423f8-1ecc-11e8-909b-4a01f5572265.png)

Thanks for the tip @emackey.

Hey @guycalledfrank - what's the 'proper' fix for this? I mean, seems odd to have to make the GLSL conditional based on whether our tangent generator is being used. Isn't it just that we can 'fix' the generator?

**Comment by UX3D-schottenheimer** [comment] 2019-06-07 08:40
I have a similar issue with the normal's.

Normals in 3DS Max
<img width="448" alt="Screenshot_2" src="https://user-images.githubusercontent.com/49145554/59091587-f33eba80-890f-11e9-83e7-c169aaff2287.png">

Normals in Blender
![normals](https://user-images.githubusercontent.com/49145554/59091162-056c2900-890f-11e9-87b9-51b3407dcc67.png)

Arnold Renderer of 3DS Max
![renderarnold](https://user-images.githubusercontent.com/49145554/59091163-056c2900-890f-11e9-8c03-3312fd8e17f2.png)

Apperience in gltf viewer
<img width="475" alt="Screenshot_1" src="https://user-images.githubusercontent.com/49145554/59091586-f33eba80-890f-11e9-8a5a-71f65099ac47.png">

<img width="302" alt="Screenshot_3" src="https://user-images.githubusercontent.com/49145554/59091588-f33eba80-890f-11e9-95a1-7711ba910786.png">

I am not so sure what could be the problem here exactly. I can't quite figure it out.
It only seems to be an issue with highly metallic materials.

**Comment by willeastcott** [comment] 2019-06-07 17:20
Can you share your scene file to enable us to reproduce the problem?

**Comment by UX3D-schottenheimer** [comment] 2019-06-11 07:24
Here you go
Sorry it was a long weekend and I had no access to the files
https://drive.google.com/file/d/1uJYmJsqEpuBPHSFsQxnrfc_exgi2X9-Q/view?usp=sharing

**Comment by willeastcott** [comment] 2022-01-25 13:12
Closing since glTF support is now available in the core engine.

**Closed by willeastcott** 2022-01-25 13:12 UTC
Labels: bug
